version: '3.6'
services:
  react:
    container_name: react_app
    image: 'node:latest'
    working_dir: /home/node/app
    command: 
      - bash
      - -c
      - 'npm install && npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./app:/home/node/app